# Site settings
title: "Krishna Deep Yerramallu"
description: "Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Krishna Deep Yerramallu"
resume_title:                   "M.Sc Computer Sciences, Ex - SiLabs, RA"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "krishnadeep.y@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+1 (516)-754-1373"
resume_contact_address:         "Castle Point, Hoboken"

resume_header_contact_info:     "Castle Point, Hoboken, (516)-754-1373, krishnadeep.y@gmail.com"
display_header_contact_info:    "false"

# resume_header_intro: "<p>This is the executive summary. You should write a few brief, concise, and meaningful sentences about yourself from a professional context, and your immediate career goals. Make the length appropriate for your needs, but keep it brief and concise</p>"
resume_header_intro: "<p>I’m currently diving deep into my Master’s in Computer Science at Stevens Institute of Technology, New Jersey, USA and worked as an Analyst / Data Engineer at Silicon Labs. I’ve got hands-on experience crafting Python and Go scripts to automate data tasks, optimising SQL queries and databases, building data pipelines in Azure and migrating legacy systems to the cloud. I also love building business intelligence tools and have a background in using machine learning for early-stage breast cancer research. Always excited to tackle new challenges and drive innovative solutions!</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
#resume_section_links:           true
resume_section_associations:    true
#resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/krishnadeepy"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  #resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/krishna-deep-yerramallu/"
  #resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  resume_medium_url:            "https://medium.com/@krishnadeep"
resume_print_social_links:      true

# Design settings
resume_theme:                   default